### ISSUE TITLE
Drop-down Menu

### ISSUE THREAD

**Issue by Nemet-design** [apogeegurus/junk-deal#20] opened 2019-12-15 05:50 UTC
Can we please make drop-down menu looks like shown in Zeplin (background, fonts size,  colors, shadow, etc.) Thank you
<img width="415" alt="Screen Shot 2019-12-14 at 21 44 10" src="https://user-images.githubusercontent.com/58584347/70858703-bc97bd00-1ebb-11ea-9d2e-a23e4663d250.png">
<img width="439" alt="Screen Shot 2019-12-14 at 21 45 27" src="https://user-images.githubusercontent.com/58584347/70858704-bd305380-1ebb-11ea-8e1e-b8fcca2e3c0d.png">

**Comment by apogeegurus** [comment] 2019-12-17 17:19
This issue is a duplicate of #13

**Closed by apogeegurus** 2019-12-17 17:19 UTC
Labels: bug
